"""Add partner_id to User model

Revision ID: 2fee7d9f5d87
Revises: 
Create Date: 2024-12-03 22:50:56.588068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fee7d9f5d87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['partner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('partner_id')

    # ### end Alembic commands ###
