"""Add paired_user_id to User with named constraint

Revision ID: 48681331bb81
Revises: 
Create Date: 2024-12-04 00:09:40.109516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48681331bb81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paired_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_paired_user_id', 'user', ['paired_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_paired_user_id', type_='foreignkey')
        batch_op.drop_column('paired_user_id')

    # ### end Alembic commands ###
