"""Add partner_id with named constraint

Revision ID: b7ee6d6510eb
Revises: 
Create Date: 2024-12-03 22:59:59.678167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ee6d6510eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_partner_id', 'user', ['partner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_partner_id', type_='foreignkey')
        batch_op.drop_column('partner_id')

    # ### end Alembic commands ###
